#!/bin/bash
SECONDS=0
echo "perform sudo apt-get update"
sudo apt-get update||echo "failed: sudo apt-get update"
echo "perform sudo apt-get -y install net-tools"
sudo apt-get -y install net-tools||echo "failed: sudo apt-get -y install net-tools"
echo "perform sudo apt-get -y install iw"
sudo apt-get -y install iw||echo "failed: sudo apt-get -y install iw"
echo "perform sudo apt-get -y install make"
sudo apt-get -y install make||echo "failed: apt-get -y install make"
echo "perform sudo apt-get -y install dkms"
sudo apt-get -y install dkms||echo "failed: sudo apt-get -y install dkms"
echo "perform sudo apt-get -y install tshark"
sudo apt-get -y install tshark||echo "failed: sudo apt-get -y install tshark"
echo "perform sudo apt-get install screen"
sudo apt-get -y install screen||echo "failed: sudo apt-get install screen"
sudo apt-get -y install dphys-swapfile||echo "failed: sudo apt-get -y install dphys-swapfile"
echo "perform sudo chmod +x /usr/bin/dumpcap"
sudo chmod +x /usr/bin/dumpcap||echo "failed: sudo apt-get update"
duration=$SECONDS
echo "Installation needed:"
echo "$((duration / 60)) minutes and $((duration % 60)) seconds elapsed."
echo "reboot needed"
